$repo='https://github.com/TabotCharlesBessong/advanced_database'
$issues=@(
[pscustomobject]@{title='P6 W29-30: Set up React development environment'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 29-30: React UI Foundation`n`n## Objective`nSet up React development environment.`n`n## Acceptance Criteria`n- React project scaffolded with TypeScript and build tooling`n- Local development server and production build both work'}
[pscustomobject]@{title='P6 W29-30: Create basic UI layout and navigation'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 29-30: React UI Foundation`n`n## Objective`nCreate basic UI layout and navigation.`n`n## Acceptance Criteria`n- Main layout includes workspace regions (sidebar, editor, result area)`n- Navigation supports switching between key views'}
[pscustomobject]@{title='P6 W29-30: Implement connection management'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 29-30: React UI Foundation`n`n## Objective`nImplement connection management.`n`n## Acceptance Criteria`n- UI supports API endpoint configuration and session connection/disconnection`n- Connection state and errors are clearly shown to the user'}
[pscustomobject]@{title='P6 W29-30: Build SQL editor component'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 29-30: React UI Foundation`n`n## Objective`nBuild SQL editor component.`n`n## Acceptance Criteria`n- SQL text input supports executing queries against the API`n- Editor integrates with query result display'}
[pscustomobject]@{title='P6 W31-32: Implement table explorer'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 31-32: Core UI Components`n`n## Objective`nImplement table explorer.`n`n## Acceptance Criteria`n- Tables are listed and selectable from the UI`n- Table metadata is accessible from explorer interactions'}
[pscustomobject]@{title='P6 W31-32: Create query result viewer'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 31-32: Core UI Components`n`n## Objective`nCreate query result viewer.`n`n## Acceptance Criteria`n- Query results render in a readable grid/table format`n- Large result sets are handled with stable performance'}
[pscustomobject]@{title='P6 W31-32: Add schema visualization'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 31-32: Core UI Components`n`n## Objective`nAdd schema visualization.`n`n## Acceptance Criteria`n- Schema relationships can be viewed in a dedicated UI area`n- Schema view updates when selected database objects change'}
[pscustomobject]@{title='P6 W31-32: Build data editing capabilities'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 31-32: Core UI Components`n`n## Objective`nBuild data editing capabilities.`n`n## Acceptance Criteria`n- UI supports insert/update/delete operations through validated forms`n- Data edit actions show success/failure feedback'}
[pscustomobject]@{title='P6 W33-34: Add query history and favorites'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 33-34: Advanced UI Features`n`n## Objective`nAdd query history and favorites.`n`n## Acceptance Criteria`n- Users can revisit previous queries`n- Frequently used queries can be saved as favorites'}
[pscustomobject]@{title='P6 W33-34: Implement export/import functionality'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 33-34: Advanced UI Features`n`n## Objective`nImplement export/import functionality.`n`n## Acceptance Criteria`n- Query/table data can be exported in supported formats`n- UI supports importing supported data files with validation'}
[pscustomobject]@{title='P6 W33-34: Create user preferences'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 33-34: Advanced UI Features`n`n## Objective`nCreate user preferences.`n`n## Acceptance Criteria`n- Users can persist key UI preferences`n- Preferences load correctly when the app restarts'}
[pscustomobject]@{title='P6 W33-34: Add performance monitoring dashboard'; body='## Parent Epic`nPhase 6 (Weeks 29-34): User Interface Development`n`n## Section`nWeek 33-34: Advanced UI Features`n`n## Objective`nAdd performance monitoring dashboard.`n`n## Acceptance Criteria`n- UI displays key performance indicators from API/database`n- Metrics update in near real-time or on refresh'}
)

$links = $issues | ForEach-Object {
  $title=[uri]::EscapeDataString($_.title)
  $body=[uri]::EscapeDataString($_.body)
  "$repo/issues/new?title=$title&body=$body"
}
$links | Set-Content -Path 'phase6-child-issue-links.txt'
$links
