$repo='https://github.com/TabotCharlesBessong/advanced_database'
$issues=@(
[pscustomobject]@{title='P2 Storage: Storage config and page size constants'; body='## Parent Epic`nPhase 2 (Weeks 5-6): Data Storage Foundation`n`n## Scope`nDefine storage-wide constants and configuration for page and file behavior.`n`n## Tasks`n- Add page size constant(s) (4KB/8KB selectable)`n- Define storage config struct/class`n- Add defaults and override path for tests`n- Document configuration options`n`n## Acceptance Criteria`n- Config compiles and is consumed by storage components`n- Unit test confirms default and override values'}
[pscustomobject]@{title='P2 Storage: FileManager create/open/read/write/flush API'; body='## Parent Epic`nPhase 2 (Weeks 5-6): Data Storage Foundation`n`n## Scope`nImplement low-level file operations abstraction for storage layer.`n`n## Tasks`n- Implement create/open/close file APIs`n- Implement page read/write by offset`n- Implement flush/sync behavior`n- Return clear error codes/messages`n`n## Acceptance Criteria`n- Read/write roundtrip test passes`n- Flush persists data across process restart'}
[pscustomobject]@{title='P2 Storage: Page struct and page header format'; body='## Parent Epic`nPhase 2 (Weeks 5-6): Data Storage Foundation`n`n## Scope`nDefine in-memory and on-disk page layout/header format.`n`n## Tasks`n- Define page header fields (id, flags, checksum/version)`n- Define payload boundaries`n- Add helpers for header encode/decode`n- Document binary layout`n`n## Acceptance Criteria`n- Header serialization tests pass`n- Backward-compatible version marker is present'}
[pscustomobject]@{title='P2 Storage: Page serialization and checksum validation'; body='## Parent Epic`nPhase 2 (Weeks 5-6): Data Storage Foundation`n`n## Scope`nImplement page encode/decode path with corruption checks.`n`n## Tasks`n- Implement serialize/deserialize functions`n- Add checksum generation/verification`n- Handle invalid/corrupt page errors`n- Add negative tests for checksum mismatch`n`n## Acceptance Criteria`n- Valid pages deserialize correctly`n- Corrupt pages are detected and rejected'}
[pscustomobject]@{title='P2 Storage: BufferPool frame lifecycle (load/evict/dirty)'; body='## Parent Epic`nPhase 2 (Weeks 5-6): Data Storage Foundation`n`n## Scope`nImplement frame management in buffer pool.`n`n## Tasks`n- Implement page load into frame`n- Track dirty/clean state`n- Implement eviction flow with write-back`n- Add frame table bookkeeping`n`n## Acceptance Criteria`n- Dirty pages are flushed before eviction`n- Frame lifecycle tests pass'}
[pscustomobject]@{title='P2 Storage: LRU replacer and pin/unpin semantics'; body='## Parent Epic`nPhase 2 (Weeks 5-6): Data Storage Foundation`n`n## Scope`nAdd page replacement and pinning semantics in buffer pool.`n`n## Tasks`n- Implement LRU replacer`n- Pin pages to prevent eviction`n- Unpin pages and reinsert into replacer`n- Add stress test for repeated pin/unpin`n`n## Acceptance Criteria`n- Pinned pages are never evicted`n- LRU selection behavior is deterministic under test'}
[pscustomobject]@{title='P2 Storage: Storage unit tests and micro-benchmark harness'; body='## Parent Epic`nPhase 2 (Weeks 5-6): Data Storage Foundation`n`n## Scope`nCreate coverage and baseline performance checks for storage.`n`n## Tasks`n- Add unit tests for FileManager/Page/BufferPool`n- Add benchmark for sequential/random page I/O`n- Export baseline metrics to docs/results`n`n## Acceptance Criteria`n- Test suite passes in CI`n- Baseline benchmark output is captured'}
[pscustomobject]@{title='P2 Catalog: Catalog schema model (tables, columns, types)'; body='## Parent Epic`nPhase 2 (Weeks 7-8): Table Management System`n`n## Scope`nDesign catalog entities for table metadata.`n`n## Tasks`n- Define TableDef, ColumnDef, TypeDef`n- Add constraints for names/types/nullability`n- Add serialization contracts for model`n`n## Acceptance Criteria`n- Catalog schema model supports MVP types`n- Validation tests for model rules pass'}
[pscustomobject]@{title='P2 Catalog: Metadata persistence format for catalog pages'; body='## Parent Epic`nPhase 2 (Weeks 7-8): Table Management System`n`n## Scope`nPersist catalog metadata in dedicated pages/files.`n`n## Tasks`n- Define on-disk format for catalog records`n- Implement read/write for metadata pages`n- Add versioning field for future migrations`n`n## Acceptance Criteria`n- Table metadata survives process restart`n- Backward compatibility marker exists'}
[pscustomobject]@{title='P2 Catalog: CREATE TABLE execution path'; body='## Parent Epic`nPhase 2 (Weeks 7-8): Table Management System`n`n## Scope`nImplement CREATE TABLE flow from command to metadata persistence.`n`n## Tasks`n- Parse/validate create table input`n- Create catalog entry`n- Create physical table backing structure`n- Return success/error response`n`n## Acceptance Criteria`n- CREATE TABLE creates catalog + storage artifacts`n- Duplicate table name returns expected error'}
[pscustomobject]@{title='P2 Catalog: Type system v1 (INT, VARCHAR, TEXT)'; body='## Parent Epic`nPhase 2 (Weeks 7-8): Table Management System`n`n## Scope`nImplement core type definitions and constraints.`n`n## Tasks`n- Add INT/VARCHAR/TEXT types`n- Add varchar length checks`n- Add value encoding/decoding hooks`n`n## Acceptance Criteria`n- Type validation works for valid/invalid inputs`n- Serialization hooks are covered by tests'}
[pscustomobject]@{title='P2 Catalog: Schema validation rules and error codes'; body='## Parent Epic`nPhase 2 (Weeks 7-8): Table Management System`n`n## Scope`nStandardize schema validation and error handling for table definitions.`n`n## Tasks`n- Implement naming/type validation rules`n- Add reusable error code enum/messages`n- Add tests for common invalid schemas`n`n## Acceptance Criteria`n- Validation errors are deterministic and descriptive`n- Negative tests cover required rule set'}
[pscustomobject]@{title='P2 Catalog: Catalog query API (getTable, listTables)'; body='## Parent Epic`nPhase 2 (Weeks 7-8): Table Management System`n`n## Scope`nAdd read APIs over catalog metadata.`n`n## Tasks`n- Implement getTable(name)`n- Implement listTables()`n- Add not-found/error handling`n`n## Acceptance Criteria`n- API returns expected metadata objects`n- Tests pass for empty and populated catalog'}
[pscustomobject]@{title='P2 Catalog: Table management integration tests'; body='## Parent Epic`nPhase 2 (Weeks 7-8): Table Management System`n`n## Scope`nEnd-to-end tests for create and metadata operations.`n`n## Tasks`n- Add integration tests for create/list/get`n- Add restart-persistence scenario`n- Add duplicate/invalid schema scenarios`n`n## Acceptance Criteria`n- Integration suite passes consistently`n- Persistence across restart is verified'}
[pscustomobject]@{title='P2 CRUD: Tuple layout and record serializer/deserializer'; body='## Parent Epic`nPhase 2 (Weeks 9-10): Basic CRUD Operations`n`n## Scope`nDefine tuple representation and record encoding.`n`n## Tasks`n- Define tuple header/field offsets`n- Implement serialize/deserialize for row values`n- Handle null/variable-length field cases`n`n## Acceptance Criteria`n- Roundtrip serialization tests pass`n- Mixed-type rows are encoded correctly'}
[pscustomobject]@{title='P2 CRUD: INSERT executor with type validation'; body='## Parent Epic`nPhase 2 (Weeks 9-10): Basic CRUD Operations`n`n## Scope`nImplement insert flow with schema/type checks.`n`n## Tasks`n- Validate column count and types`n- Serialize tuple and write to table storage`n- Return inserted row count/status`n`n## Acceptance Criteria`n- Valid inserts persist rows`n- Invalid inserts fail with clear errors'}
[pscustomobject]@{title='P2 CRUD: Table scan iterator for SELECT'; body='## Parent Epic`nPhase 2 (Weeks 9-10): Basic CRUD Operations`n`n## Scope`nImplement sequential scan over table pages/rows.`n`n## Tasks`n- Implement iterator interface for table scan`n- Skip tombstoned/invalid rows`n- Return rows in stable scan order`n`n## Acceptance Criteria`n- Full scan returns all inserted rows`n- Iterator behavior is validated by tests'}
[pscustomobject]@{title='P2 CRUD: WHERE predicate evaluator (equality first)'; body='## Parent Epic`nPhase 2 (Weeks 9-10): Basic CRUD Operations`n`n## Scope`nAdd predicate filtering support for simple WHERE expressions.`n`n## Tasks`n- Implement equality comparator per type`n- Integrate predicate check into scan`n- Add null and mismatch handling`n`n## Acceptance Criteria`n- Equality filters return expected subsets`n- Predicate tests cover type mismatch scenarios'}
[pscustomobject]@{title='P2 CRUD: SELECT projection and row materialization'; body='## Parent Epic`nPhase 2 (Weeks 9-10): Basic CRUD Operations`n`n## Scope`nSupport column projection and result row shaping.`n`n## Tasks`n- Implement select-list projection`n- Materialize output rows in selected column order`n- Support wildcard select for MVP`n`n## Acceptance Criteria`n- Projected output matches schema/order requirements`n- Wildcard and explicit projection tests pass'}
[pscustomobject]@{title='P2 CRUD: CRUD end-to-end tests with fixture datasets'; body='## Parent Epic`nPhase 2 (Weeks 9-10): Basic CRUD Operations`n`n## Scope`nAdd E2E tests covering insert/select/filter flows.`n`n## Tasks`n- Create fixture datasets`n- Add E2E tests for insert + select + where`n- Add restart scenario to verify persistence`n`n## Acceptance Criteria`n- E2E tests pass locally and in CI`n- Failures provide actionable diagnostics'}
[pscustomobject]@{title='P2 Parser: SQL lexer tokens and tokenizer tests'; body='## Parent Epic`nPhase 2 (Weeks 11-12): SQL Parser Foundation`n`n## Scope`nImplement lexer for SQL subset.`n`n## Tasks`n- Define token types for CREATE/INSERT/SELECT subset`n- Implement tokenizer with position tracking`n- Add tokenization tests`n`n## Acceptance Criteria`n- Lexer token stream matches expected fixtures`n- Line/column position metadata is accurate'}
[pscustomobject]@{title='P2 Parser: AST node definitions for CREATE/INSERT/SELECT'; body='## Parent Epic`nPhase 2 (Weeks 11-12): SQL Parser Foundation`n`n## Scope`nDefine AST structures for supported SQL statements.`n`n## Tasks`n- Add base AST node interfaces/types`n- Define CREATE TABLE AST nodes`n- Define INSERT and SELECT AST nodes`n`n## Acceptance Criteria`n- AST can represent MVP SQL subset`n- AST construction tests pass'}
[pscustomobject]@{title='P2 Parser: Parser for CREATE TABLE'; body='## Parent Epic`nPhase 2 (Weeks 11-12): SQL Parser Foundation`n`n## Scope`nImplement parser branch for CREATE TABLE statements.`n`n## Tasks`n- Parse table name and column definitions`n- Parse data types and constraints subset`n- Build CREATE AST nodes`n`n## Acceptance Criteria`n- Valid CREATE statements parse successfully`n- Invalid syntax returns structured parse errors'}
[pscustomobject]@{title='P2 Parser: Parser for INSERT'; body='## Parent Epic`nPhase 2 (Weeks 11-12): SQL Parser Foundation`n`n## Scope`nImplement parser branch for INSERT statements.`n`n## Tasks`n- Parse table target and optional column list`n- Parse VALUES tuples`n- Build INSERT AST nodes`n`n## Acceptance Criteria`n- Supported INSERT forms parse correctly`n- Syntax and arity errors are detected'}
[pscustomobject]@{title='P2 Parser: Parser for SELECT + simple WHERE'; body='## Parent Epic`nPhase 2 (Weeks 11-12): SQL Parser Foundation`n`n## Scope`nImplement parser branch for SELECT with simple filters.`n`n## Tasks`n- Parse select-list and FROM table`n- Parse equality WHERE expressions`n- Build SELECT AST nodes`n`n## Acceptance Criteria`n- SELECT and SELECT+WHERE parse correctly`n- Unsupported clauses fail gracefully'}
[pscustomobject]@{title='P2 Parser: Parser diagnostics (line/column) + negative test corpus'; body='## Parent Epic`nPhase 2 (Weeks 11-12): SQL Parser Foundation`n`n## Scope`nImprove parser diagnostics and test failure cases.`n`n## Tasks`n- Emit line/column in parse errors`n- Add clear expected-token messaging`n- Add negative corpus of malformed SQL inputs`n`n## Acceptance Criteria`n- Error messages are consistent and precise`n- Negative parser test suite passes'}
)
$links = $issues | ForEach-Object {
  $title=[uri]::EscapeDataString($_.title)
  $body=[uri]::EscapeDataString($_.body)
  "$repo/issues/new?title=$title&body=$body"
}
$links | Set-Content -Path 'phase2-child-issue-links.txt'
$links