$repo='https://github.com/TabotCharlesBessong/advanced_database'
$issues=@(
[pscustomobject]@{title='P4 W19-20: Implement B-Tree data structure'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 19-20: B-Tree Index Implementation`n`n## Objective`nImplement B-Tree data structure.`n`n## Acceptance Criteria`n- B-Tree supports insert/search operations for indexed keys`n- Core B-Tree behavior is validated with unit tests'}
[pscustomobject]@{title='P4 W19-20: Create index creation and maintenance'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 19-20: B-Tree Index Implementation`n`n## Objective`nCreate index creation and maintenance.`n`n## Acceptance Criteria`n- Indexes can be created on supported column types`n- Index entries are maintained on row insert/update/delete paths'}
[pscustomobject]@{title='P4 W19-20: Support point queries and range scans'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 19-20: B-Tree Index Implementation`n`n## Objective`nSupport point queries and range scans.`n`n## Acceptance Criteria`n- Equality predicates can be served by index lookup`n- Range predicates (>, >=, <, <=) can be served by index scan'}
[pscustomobject]@{title='P4 W19-20: Integrate indexes with query execution'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 19-20: B-Tree Index Implementation`n`n## Objective`nIntegrate indexes with query execution.`n`n## Acceptance Criteria`n- Planner/executor can choose index access path when beneficial`n- Query correctness remains consistent with table-scan execution'}
[pscustomobject]@{title='P4 W21-22: Implement basic transaction support'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 21-22: Transaction Management`n`n## Objective`nImplement basic transaction support.`n`n## Acceptance Criteria`n- BEGIN/COMMIT/ROLLBACK lifecycle is supported`n- Multi-statement transactions preserve atomicity for supported operations'}
[pscustomobject]@{title='P4 W21-22: Add Write-Ahead Logging (WAL)'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 21-22: Transaction Management`n`n## Objective`nAdd Write-Ahead Logging (WAL).`n`n## Acceptance Criteria`n- WAL records changes before data pages are persisted`n- Recovery can replay/undo changes from WAL'}
[pscustomobject]@{title='P4 W21-22: Support BEGIN, COMMIT, ROLLBACK'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 21-22: Transaction Management`n`n## Objective`nSupport BEGIN, COMMIT, ROLLBACK.`n`n## Acceptance Criteria`n- SQL parser and engine accept transaction commands`n- Transaction state transitions are validated by tests'}
[pscustomobject]@{title='P4 W21-22: Ensure atomicity and durability'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 21-22: Transaction Management`n`n## Objective`nEnsure atomicity and durability.`n`n## Acceptance Criteria`n- Crash/restart test demonstrates committed data durability`n- Partially applied transactions are not visible after recovery'}
[pscustomobject]@{title='P4 W23-24: Implement locking mechanisms'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 23-24: Concurrency Control`n`n## Objective`nImplement locking mechanisms.`n`n## Acceptance Criteria`n- Lock manager supports shared/exclusive semantics`n- Conflicting operations are serialized correctly'}
[pscustomobject]@{title='P4 W23-24: Add MVCC support'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 23-24: Concurrency Control`n`n## Objective`nAdd Multi-Version Concurrency Control (MVCC).`n`n## Acceptance Criteria`n- Readers can access consistent snapshots without blocking writers`n- Version visibility rules are documented and tested'}
[pscustomobject]@{title='P4 W23-24: Support concurrent transactions'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 23-24: Concurrency Control`n`n## Objective`nSupport concurrent transactions.`n`n## Acceptance Criteria`n- Concurrent workloads execute without violating consistency`n- Isolation behavior matches selected isolation level(s)'}
[pscustomobject]@{title='P4 W23-24: Handle deadlock detection and resolution'; body='## Parent Epic`nPhase 4 (Weeks 19-24): Indexing and Performance`n`n## Section`nWeek 23-24: Concurrency Control`n`n## Objective`nHandle deadlock detection and resolution.`n`n## Acceptance Criteria`n- Deadlocks are detected within bounded time`n- Victim selection and rollback policy are implemented and tested'}
)

$links = $issues | ForEach-Object {
  $title=[uri]::EscapeDataString($_.title)
  $body=[uri]::EscapeDataString($_.body)
  "$repo/issues/new?title=$title&body=$body"
}
$links | Set-Content -Path 'phase4-child-issue-links.txt'
$links
